/* Additional record code for MOSES.Simulations.ACTS_adsorption generated by the OpenModelica Compiler OpenModelica v1.16.5 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "MOSES.Simulations.ACTS_adsorption_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MOSES_MassTransfer_sorbate_FluidConstants__desc_added 1
const char* MOSES_MassTransfer_sorbate_FluidConstants__desc__fields[28] = {"iupacName","casRegistryNumber","chemicalFormula","structureFormula","molarMass","criticalTemperature","criticalPressure","criticalMolarVolume","acentricFactor","triplePointTemperature","triplePointPressure","meltingPoint","normalBoilingPoint","dipoleMoment","hasIdealGasHeatCapacity","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasAccurateViscosityData","hasAccurateConductivityData","hasVapourPressureCurve","hasAcentricFactor","HCRIT0","SCRIT0","deltah","deltas"};
struct record_description MOSES_MassTransfer_sorbate_FluidConstants__desc = {
  "MOSES_MassTransfer_sorbate_FluidConstants", /* package_record__X */
  "MOSES.MassTransfer.sorbate.FluidConstants", /* package.record_X */
  MOSES_MassTransfer_sorbate_FluidConstants__desc__fields
};

void MOSES_MassTransfer_sorbate_FluidConstants_construct_p(threadData_t *threadData, void* v_ths ) {
  MOSES_MassTransfer_sorbate_FluidConstants* ths = (MOSES_MassTransfer_sorbate_FluidConstants*)(v_ths);
  // ths->_iupacName has no default value.
  // ths->_casRegistryNumber has no default value.
  // ths->_chemicalFormula has no default value.
  // ths->_structureFormula has no default value.
  // ths->_molarMass has no default value.
  // ths->_criticalTemperature has no default value.
  // ths->_criticalPressure has no default value.
  // ths->_criticalMolarVolume has no default value.
  // ths->_acentricFactor has no default value.
  // ths->_triplePointTemperature has no default value.
  // ths->_triplePointPressure has no default value.
  // ths->_meltingPoint has no default value.
  // ths->_normalBoilingPoint has no default value.
  // ths->_dipoleMoment has no default value.
  ths->_hasIdealGasHeatCapacity = 0;
  ths->_hasCriticalData = 0;
  ths->_hasDipoleMoment = 0;
  ths->_hasFundamentalEquation = 0;
  ths->_hasLiquidHeatCapacity = 0;
  ths->_hasSolidHeatCapacity = 0;
  ths->_hasAccurateViscosityData = 0;
  ths->_hasAccurateConductivityData = 0;
  ths->_hasVapourPressureCurve = 0;
  ths->_hasAcentricFactor = 0;
  ths->_HCRIT0 = 0.0;
  ths->_SCRIT0 = 0.0;
  ths->_deltah = 0.0;
  ths->_deltas = 0.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
MOSES_MassTransfer_sorbate_FluidConstants omc_MOSES_MassTransfer_sorbate_FluidConstants(threadData_t *threadData , modelica_string  in_iupacName, modelica_string  in_casRegistryNumber, modelica_string  in_chemicalFormula, modelica_string  in_structureFormula, modelica_real  in_molarMass, modelica_real  in_criticalTemperature, modelica_real  in_criticalPressure, modelica_real  in_criticalMolarVolume, modelica_real  in_acentricFactor, modelica_real  in_triplePointTemperature, modelica_real  in_triplePointPressure, modelica_real  in_meltingPoint, modelica_real  in_normalBoilingPoint, modelica_real  in_dipoleMoment, modelica_boolean  in_hasIdealGasHeatCapacity, modelica_boolean  in_hasCriticalData, modelica_boolean  in_hasDipoleMoment, modelica_boolean  in_hasFundamentalEquation, modelica_boolean  in_hasLiquidHeatCapacity, modelica_boolean  in_hasSolidHeatCapacity, modelica_boolean  in_hasAccurateViscosityData, modelica_boolean  in_hasAccurateConductivityData, modelica_boolean  in_hasVapourPressureCurve, modelica_boolean  in_hasAcentricFactor, modelica_real  in_HCRIT0, modelica_real  in_SCRIT0, modelica_real  in_deltah, modelica_real  in_deltas) {
  MOSES_MassTransfer_sorbate_FluidConstants dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in MOSES_MassTransfer_sorbate_FluidConstants_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  MOSES_MassTransfer_sorbate_FluidConstants_construct(threadData, dst);
  dst._iupacName =  in_iupacName;
  dst._casRegistryNumber =  in_casRegistryNumber;
  dst._chemicalFormula =  in_chemicalFormula;
  dst._structureFormula =  in_structureFormula;
  dst._molarMass =  in_molarMass;
  dst._criticalTemperature =  in_criticalTemperature;
  dst._criticalPressure =  in_criticalPressure;
  dst._criticalMolarVolume =  in_criticalMolarVolume;
  dst._acentricFactor =  in_acentricFactor;
  dst._triplePointTemperature =  in_triplePointTemperature;
  dst._triplePointPressure =  in_triplePointPressure;
  dst._meltingPoint =  in_meltingPoint;
  dst._normalBoilingPoint =  in_normalBoilingPoint;
  dst._dipoleMoment =  in_dipoleMoment;
  dst._hasIdealGasHeatCapacity =  in_hasIdealGasHeatCapacity;
  dst._hasCriticalData =  in_hasCriticalData;
  dst._hasDipoleMoment =  in_hasDipoleMoment;
  dst._hasFundamentalEquation =  in_hasFundamentalEquation;
  dst._hasLiquidHeatCapacity =  in_hasLiquidHeatCapacity;
  dst._hasSolidHeatCapacity =  in_hasSolidHeatCapacity;
  dst._hasAccurateViscosityData =  in_hasAccurateViscosityData;
  dst._hasAccurateConductivityData =  in_hasAccurateConductivityData;
  dst._hasVapourPressureCurve =  in_hasVapourPressureCurve;
  dst._hasAcentricFactor =  in_hasAcentricFactor;
  dst._HCRIT0 =  in_HCRIT0;
  dst._SCRIT0 =  in_SCRIT0;
  dst._deltah =  in_deltah;
  dst._deltas =  in_deltas;
  return dst;
}
*/

void MOSES_MassTransfer_sorbate_FluidConstants_copy_p(void* v_src, void* v_dst) {
  MOSES_MassTransfer_sorbate_FluidConstants* src = (MOSES_MassTransfer_sorbate_FluidConstants*)(v_src);
  MOSES_MassTransfer_sorbate_FluidConstants* dst = (MOSES_MassTransfer_sorbate_FluidConstants*)(v_dst);
  dst->_iupacName = src->_iupacName;
  dst->_casRegistryNumber = src->_casRegistryNumber;
  dst->_chemicalFormula = src->_chemicalFormula;
  dst->_structureFormula = src->_structureFormula;
  dst->_molarMass = src->_molarMass;
  dst->_criticalTemperature = src->_criticalTemperature;
  dst->_criticalPressure = src->_criticalPressure;
  dst->_criticalMolarVolume = src->_criticalMolarVolume;
  dst->_acentricFactor = src->_acentricFactor;
  dst->_triplePointTemperature = src->_triplePointTemperature;
  dst->_triplePointPressure = src->_triplePointPressure;
  dst->_meltingPoint = src->_meltingPoint;
  dst->_normalBoilingPoint = src->_normalBoilingPoint;
  dst->_dipoleMoment = src->_dipoleMoment;
  dst->_hasIdealGasHeatCapacity = src->_hasIdealGasHeatCapacity;
  dst->_hasCriticalData = src->_hasCriticalData;
  dst->_hasDipoleMoment = src->_hasDipoleMoment;
  dst->_hasFundamentalEquation = src->_hasFundamentalEquation;
  dst->_hasLiquidHeatCapacity = src->_hasLiquidHeatCapacity;
  dst->_hasSolidHeatCapacity = src->_hasSolidHeatCapacity;
  dst->_hasAccurateViscosityData = src->_hasAccurateViscosityData;
  dst->_hasAccurateConductivityData = src->_hasAccurateConductivityData;
  dst->_hasVapourPressureCurve = src->_hasVapourPressureCurve;
  dst->_hasAcentricFactor = src->_hasAcentricFactor;
  dst->_HCRIT0 = src->_HCRIT0;
  dst->_SCRIT0 = src->_SCRIT0;
  dst->_deltah = src->_deltah;
  dst->_deltas = src->_deltas;
}

#define Modelica_Media_Common_GibbsDerivs__desc_added 1
const char* Modelica_Media_Common_GibbsDerivs__desc__fields[11] = {"p","T","R_s","pi","tau","g","gpi","gpipi","gtau","gtautau","gtaupi"};
struct record_description Modelica_Media_Common_GibbsDerivs__desc = {
  "Modelica_Media_Common_GibbsDerivs", /* package_record__X */
  "Modelica.Media.Common.GibbsDerivs", /* package.record_X */
  Modelica_Media_Common_GibbsDerivs__desc__fields
};

void Modelica_Media_Common_GibbsDerivs_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_GibbsDerivs* ths = (Modelica_Media_Common_GibbsDerivs*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  // ths->_R_s has no default value.
  // ths->_pi has no default value.
  // ths->_tau has no default value.
  // ths->_g has no default value.
  // ths->_gpi has no default value.
  // ths->_gpipi has no default value.
  // ths->_gtau has no default value.
  // ths->_gtautau has no default value.
  // ths->_gtaupi has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_GibbsDerivs omc_Modelica_Media_Common_GibbsDerivs(threadData_t *threadData , modelica_real  in_p, modelica_real  in_T, modelica_real  in_R_s, modelica_real  in_pi, modelica_real  in_tau, modelica_real  in_g, modelica_real  in_gpi, modelica_real  in_gpipi, modelica_real  in_gtau, modelica_real  in_gtautau, modelica_real  in_gtaupi) {
  Modelica_Media_Common_GibbsDerivs dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_GibbsDerivs_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_GibbsDerivs_construct(threadData, dst);
  dst._p =  in_p;
  dst._T =  in_T;
  dst._R_s =  in_R_s;
  dst._pi =  in_pi;
  dst._tau =  in_tau;
  dst._g =  in_g;
  dst._gpi =  in_gpi;
  dst._gpipi =  in_gpipi;
  dst._gtau =  in_gtau;
  dst._gtautau =  in_gtautau;
  dst._gtaupi =  in_gtaupi;
  return dst;
}
*/

void Modelica_Media_Common_GibbsDerivs_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_GibbsDerivs* src = (Modelica_Media_Common_GibbsDerivs*)(v_src);
  Modelica_Media_Common_GibbsDerivs* dst = (Modelica_Media_Common_GibbsDerivs*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  dst->_R_s = src->_R_s;
  dst->_pi = src->_pi;
  dst->_tau = src->_tau;
  dst->_g = src->_g;
  dst->_gpi = src->_gpi;
  dst->_gpipi = src->_gpipi;
  dst->_gtau = src->_gtau;
  dst->_gtautau = src->_gtautau;
  dst->_gtaupi = src->_gtaupi;
}

#define Modelica_Media_Common_HelmholtzDerivs__desc_added 1
const char* Modelica_Media_Common_HelmholtzDerivs__desc__fields[11] = {"d","T","R_s","delta","tau","f","fdelta","fdeltadelta","ftau","ftautau","fdeltatau"};
struct record_description Modelica_Media_Common_HelmholtzDerivs__desc = {
  "Modelica_Media_Common_HelmholtzDerivs", /* package_record__X */
  "Modelica.Media.Common.HelmholtzDerivs", /* package.record_X */
  Modelica_Media_Common_HelmholtzDerivs__desc__fields
};

void Modelica_Media_Common_HelmholtzDerivs_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_HelmholtzDerivs* ths = (Modelica_Media_Common_HelmholtzDerivs*)(v_ths);
  // ths->_d has no default value.
  // ths->_T has no default value.
  // ths->_R_s has no default value.
  // ths->_delta has no default value.
  // ths->_tau has no default value.
  // ths->_f has no default value.
  // ths->_fdelta has no default value.
  // ths->_fdeltadelta has no default value.
  // ths->_ftau has no default value.
  // ths->_ftautau has no default value.
  // ths->_fdeltatau has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_HelmholtzDerivs omc_Modelica_Media_Common_HelmholtzDerivs(threadData_t *threadData , modelica_real  in_d, modelica_real  in_T, modelica_real  in_R_s, modelica_real  in_delta, modelica_real  in_tau, modelica_real  in_f, modelica_real  in_fdelta, modelica_real  in_fdeltadelta, modelica_real  in_ftau, modelica_real  in_ftautau, modelica_real  in_fdeltatau) {
  Modelica_Media_Common_HelmholtzDerivs dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_HelmholtzDerivs_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_HelmholtzDerivs_construct(threadData, dst);
  dst._d =  in_d;
  dst._T =  in_T;
  dst._R_s =  in_R_s;
  dst._delta =  in_delta;
  dst._tau =  in_tau;
  dst._f =  in_f;
  dst._fdelta =  in_fdelta;
  dst._fdeltadelta =  in_fdeltadelta;
  dst._ftau =  in_ftau;
  dst._ftautau =  in_ftautau;
  dst._fdeltatau =  in_fdeltatau;
  return dst;
}
*/

void Modelica_Media_Common_HelmholtzDerivs_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_HelmholtzDerivs* src = (Modelica_Media_Common_HelmholtzDerivs*)(v_src);
  Modelica_Media_Common_HelmholtzDerivs* dst = (Modelica_Media_Common_HelmholtzDerivs*)(v_dst);
  dst->_d = src->_d;
  dst->_T = src->_T;
  dst->_R_s = src->_R_s;
  dst->_delta = src->_delta;
  dst->_tau = src->_tau;
  dst->_f = src->_f;
  dst->_fdelta = src->_fdelta;
  dst->_fdeltadelta = src->_fdeltadelta;
  dst->_ftau = src->_ftau;
  dst->_ftautau = src->_ftautau;
  dst->_fdeltatau = src->_fdeltatau;
}

#define Modelica_Media_Common_NewtonDerivatives__pT__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__pT__desc__fields[2] = {"p","pd"};
struct record_description Modelica_Media_Common_NewtonDerivatives__pT__desc = {
  "Modelica_Media_Common_NewtonDerivatives__pT", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_pT", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__pT__desc__fields
};

void Modelica_Media_Common_NewtonDerivatives__pT_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_NewtonDerivatives__pT* ths = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_ths);
  // ths->_p has no default value.
  // ths->_pd has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_NewtonDerivatives__pT omc_Modelica_Media_Common_NewtonDerivatives__pT(threadData_t *threadData , modelica_real  in_p, modelica_real  in_pd) {
  Modelica_Media_Common_NewtonDerivatives__pT dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_NewtonDerivatives__pT_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_NewtonDerivatives__pT_construct(threadData, dst);
  dst._p =  in_p;
  dst._pd =  in_pd;
  return dst;
}
*/

void Modelica_Media_Common_NewtonDerivatives__pT_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_NewtonDerivatives__pT* src = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_src);
  Modelica_Media_Common_NewtonDerivatives__pT* dst = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_dst);
  dst->_p = src->_p;
  dst->_pd = src->_pd;
}

#define Modelica_Media_Common_NewtonDerivatives__ph__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__ph__desc__fields[6] = {"p","h","pd","pt","hd","ht"};
struct record_description Modelica_Media_Common_NewtonDerivatives__ph__desc = {
  "Modelica_Media_Common_NewtonDerivatives__ph", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_ph", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__ph__desc__fields
};

void Modelica_Media_Common_NewtonDerivatives__ph_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_NewtonDerivatives__ph* ths = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
  // ths->_pd has no default value.
  // ths->_pt has no default value.
  // ths->_hd has no default value.
  // ths->_ht has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_NewtonDerivatives__ph omc_Modelica_Media_Common_NewtonDerivatives__ph(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h, modelica_real  in_pd, modelica_real  in_pt, modelica_real  in_hd, modelica_real  in_ht) {
  Modelica_Media_Common_NewtonDerivatives__ph dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_NewtonDerivatives__ph_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_NewtonDerivatives__ph_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  dst._pd =  in_pd;
  dst._pt =  in_pt;
  dst._hd =  in_hd;
  dst._ht =  in_ht;
  return dst;
}
*/

void Modelica_Media_Common_NewtonDerivatives__ph_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_NewtonDerivatives__ph* src = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_src);
  Modelica_Media_Common_NewtonDerivatives__ph* dst = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
  dst->_pd = src->_pd;
  dst->_pt = src->_pt;
  dst->_hd = src->_hd;
  dst->_ht = src->_ht;
}

#define Modelica_Media_Common_IF97BaseTwoPhase__desc_added 1
const char* Modelica_Media_Common_IF97BaseTwoPhase__desc__fields[16] = {"phase","region","p","T","h","R_s","cp","cv","rho","s","pt","pd","vt","vp","x","dpT"};
struct record_description Modelica_Media_Common_IF97BaseTwoPhase__desc = {
  "Modelica_Media_Common_IF97BaseTwoPhase", /* package_record__X */
  "Modelica.Media.Common.IF97BaseTwoPhase", /* package.record_X */
  Modelica_Media_Common_IF97BaseTwoPhase__desc__fields
};

void Modelica_Media_Common_IF97BaseTwoPhase_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_IF97BaseTwoPhase* ths = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_ths);
  // ths->_phase has no default value.
  // ths->_region has no default value.
  // ths->_p has no default value.
  // ths->_T has no default value.
  // ths->_h has no default value.
  // ths->_R_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_rho has no default value.
  // ths->_s has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
  // ths->_vt has no default value.
  // ths->_vp has no default value.
  // ths->_x has no default value.
  // ths->_dpT has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_IF97BaseTwoPhase omc_Modelica_Media_Common_IF97BaseTwoPhase(threadData_t *threadData , modelica_integer  in_phase, modelica_integer  in_region, modelica_real  in_p, modelica_real  in_T, modelica_real  in_h, modelica_real  in_R_s, modelica_real  in_cp, modelica_real  in_cv, modelica_real  in_rho, modelica_real  in_s, modelica_real  in_pt, modelica_real  in_pd, modelica_real  in_vt, modelica_real  in_vp, modelica_real  in_x, modelica_real  in_dpT) {
  Modelica_Media_Common_IF97BaseTwoPhase dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_IF97BaseTwoPhase_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_IF97BaseTwoPhase_construct(threadData, dst);
  dst._phase =  in_phase;
  dst._region =  in_region;
  dst._p =  in_p;
  dst._T =  in_T;
  dst._h =  in_h;
  dst._R_s =  in_R_s;
  dst._cp =  in_cp;
  dst._cv =  in_cv;
  dst._rho =  in_rho;
  dst._s =  in_s;
  dst._pt =  in_pt;
  dst._pd =  in_pd;
  dst._vt =  in_vt;
  dst._vp =  in_vp;
  dst._x =  in_x;
  dst._dpT =  in_dpT;
  return dst;
}
*/

void Modelica_Media_Common_IF97BaseTwoPhase_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_IF97BaseTwoPhase* src = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_src);
  Modelica_Media_Common_IF97BaseTwoPhase* dst = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_dst);
  dst->_phase = src->_phase;
  dst->_region = src->_region;
  dst->_p = src->_p;
  dst->_T = src->_T;
  dst->_h = src->_h;
  dst->_R_s = src->_R_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_rho = src->_rho;
  dst->_s = src->_s;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
  dst->_vt = src->_vt;
  dst->_vp = src->_vp;
  dst->_x = src->_x;
  dst->_dpT = src->_dpT;
}

#define Modelica_Media_Common_IF97PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields[13] = {"region3boundary","R_s","T","d","h","s","cp","cv","dpT","pt","pd","vt","vp"};
struct record_description Modelica_Media_Common_IF97PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_IF97PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.IF97PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields
};

void Modelica_Media_Common_IF97PhaseBoundaryProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties* ths = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_ths);
  // ths->_region3boundary has no default value.
  // ths->_R_s has no default value.
  // ths->_T has no default value.
  // ths->_d has no default value.
  // ths->_h has no default value.
  // ths->_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_dpT has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
  // ths->_vt has no default value.
  // ths->_vp has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_IF97PhaseBoundaryProperties omc_Modelica_Media_Common_IF97PhaseBoundaryProperties(threadData_t *threadData , modelica_boolean  in_region3boundary, modelica_real  in_R_s, modelica_real  in_T, modelica_real  in_d, modelica_real  in_h, modelica_real  in_s, modelica_real  in_cp, modelica_real  in_cv, modelica_real  in_dpT, modelica_real  in_pt, modelica_real  in_pd, modelica_real  in_vt, modelica_real  in_vp) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_IF97PhaseBoundaryProperties_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_IF97PhaseBoundaryProperties_construct(threadData, dst);
  dst._region3boundary =  in_region3boundary;
  dst._R_s =  in_R_s;
  dst._T =  in_T;
  dst._d =  in_d;
  dst._h =  in_h;
  dst._s =  in_s;
  dst._cp =  in_cp;
  dst._cv =  in_cv;
  dst._dpT =  in_dpT;
  dst._pt =  in_pt;
  dst._pd =  in_pd;
  dst._vt =  in_vt;
  dst._vp =  in_vp;
  return dst;
}
*/

void Modelica_Media_Common_IF97PhaseBoundaryProperties_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties* src = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_src);
  Modelica_Media_Common_IF97PhaseBoundaryProperties* dst = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_dst);
  dst->_region3boundary = src->_region3boundary;
  dst->_R_s = src->_R_s;
  dst->_T = src->_T;
  dst->_d = src->_d;
  dst->_h = src->_h;
  dst->_s = src->_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_dpT = src->_dpT;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
  dst->_vt = src->_vt;
  dst->_vp = src->_vp;
}

#define Modelica_Media_Common_PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_PhaseBoundaryProperties__desc__fields[8] = {"d","h","u","s","cp","cv","pt","pd"};
struct record_description Modelica_Media_Common_PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_PhaseBoundaryProperties__desc__fields
};

void Modelica_Media_Common_PhaseBoundaryProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_PhaseBoundaryProperties* ths = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_ths);
  // ths->_d has no default value.
  // ths->_h has no default value.
  // ths->_u has no default value.
  // ths->_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Common_PhaseBoundaryProperties omc_Modelica_Media_Common_PhaseBoundaryProperties(threadData_t *threadData , modelica_real  in_d, modelica_real  in_h, modelica_real  in_u, modelica_real  in_s, modelica_real  in_cp, modelica_real  in_cv, modelica_real  in_pt, modelica_real  in_pd) {
  Modelica_Media_Common_PhaseBoundaryProperties dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Common_PhaseBoundaryProperties_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Common_PhaseBoundaryProperties_construct(threadData, dst);
  dst._d =  in_d;
  dst._h =  in_h;
  dst._u =  in_u;
  dst._s =  in_s;
  dst._cp =  in_cp;
  dst._cv =  in_cv;
  dst._pt =  in_pt;
  dst._pd =  in_pd;
  return dst;
}
*/

void Modelica_Media_Common_PhaseBoundaryProperties_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_PhaseBoundaryProperties* src = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_src);
  Modelica_Media_Common_PhaseBoundaryProperties* dst = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_dst);
  dst->_d = src->_d;
  dst->_h = src->_h;
  dst->_u = src->_u;
  dst->_s = src->_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
}

#define Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc__fields[28] = {"iupacName","casRegistryNumber","chemicalFormula","structureFormula","molarMass","criticalTemperature","criticalPressure","criticalMolarVolume","acentricFactor","triplePointTemperature","triplePointPressure","meltingPoint","normalBoilingPoint","dipoleMoment","hasIdealGasHeatCapacity","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasAccurateViscosityData","hasAccurateConductivityData","hasVapourPressureCurve","hasAcentricFactor","HCRIT0","SCRIT0","deltah","deltas"};
struct record_description Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc = {
  "Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.TwoPhase.FluidConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc__fields
};

void Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants* ths = (Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants*)(v_ths);
  // ths->_iupacName has no default value.
  // ths->_casRegistryNumber has no default value.
  // ths->_chemicalFormula has no default value.
  // ths->_structureFormula has no default value.
  // ths->_molarMass has no default value.
  // ths->_criticalTemperature has no default value.
  // ths->_criticalPressure has no default value.
  // ths->_criticalMolarVolume has no default value.
  // ths->_acentricFactor has no default value.
  // ths->_triplePointTemperature has no default value.
  // ths->_triplePointPressure has no default value.
  // ths->_meltingPoint has no default value.
  // ths->_normalBoilingPoint has no default value.
  // ths->_dipoleMoment has no default value.
  ths->_hasIdealGasHeatCapacity = 0;
  ths->_hasCriticalData = 0;
  ths->_hasDipoleMoment = 0;
  ths->_hasFundamentalEquation = 0;
  ths->_hasLiquidHeatCapacity = 0;
  ths->_hasSolidHeatCapacity = 0;
  ths->_hasAccurateViscosityData = 0;
  ths->_hasAccurateConductivityData = 0;
  ths->_hasVapourPressureCurve = 0;
  ths->_hasAcentricFactor = 0;
  ths->_HCRIT0 = 0.0;
  ths->_SCRIT0 = 0.0;
  ths->_deltah = 0.0;
  ths->_deltas = 0.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants omc_Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants(threadData_t *threadData , modelica_string  in_iupacName, modelica_string  in_casRegistryNumber, modelica_string  in_chemicalFormula, modelica_string  in_structureFormula, modelica_real  in_molarMass, modelica_real  in_criticalTemperature, modelica_real  in_criticalPressure, modelica_real  in_criticalMolarVolume, modelica_real  in_acentricFactor, modelica_real  in_triplePointTemperature, modelica_real  in_triplePointPressure, modelica_real  in_meltingPoint, modelica_real  in_normalBoilingPoint, modelica_real  in_dipoleMoment, modelica_boolean  in_hasIdealGasHeatCapacity, modelica_boolean  in_hasCriticalData, modelica_boolean  in_hasDipoleMoment, modelica_boolean  in_hasFundamentalEquation, modelica_boolean  in_hasLiquidHeatCapacity, modelica_boolean  in_hasSolidHeatCapacity, modelica_boolean  in_hasAccurateViscosityData, modelica_boolean  in_hasAccurateConductivityData, modelica_boolean  in_hasVapourPressureCurve, modelica_boolean  in_hasAcentricFactor, modelica_real  in_HCRIT0, modelica_real  in_SCRIT0, modelica_real  in_deltah, modelica_real  in_deltas) {
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants_construct(threadData, dst);
  dst._iupacName =  in_iupacName;
  dst._casRegistryNumber =  in_casRegistryNumber;
  dst._chemicalFormula =  in_chemicalFormula;
  dst._structureFormula =  in_structureFormula;
  dst._molarMass =  in_molarMass;
  dst._criticalTemperature =  in_criticalTemperature;
  dst._criticalPressure =  in_criticalPressure;
  dst._criticalMolarVolume =  in_criticalMolarVolume;
  dst._acentricFactor =  in_acentricFactor;
  dst._triplePointTemperature =  in_triplePointTemperature;
  dst._triplePointPressure =  in_triplePointPressure;
  dst._meltingPoint =  in_meltingPoint;
  dst._normalBoilingPoint =  in_normalBoilingPoint;
  dst._dipoleMoment =  in_dipoleMoment;
  dst._hasIdealGasHeatCapacity =  in_hasIdealGasHeatCapacity;
  dst._hasCriticalData =  in_hasCriticalData;
  dst._hasDipoleMoment =  in_hasDipoleMoment;
  dst._hasFundamentalEquation =  in_hasFundamentalEquation;
  dst._hasLiquidHeatCapacity =  in_hasLiquidHeatCapacity;
  dst._hasSolidHeatCapacity =  in_hasSolidHeatCapacity;
  dst._hasAccurateViscosityData =  in_hasAccurateViscosityData;
  dst._hasAccurateConductivityData =  in_hasAccurateConductivityData;
  dst._hasVapourPressureCurve =  in_hasVapourPressureCurve;
  dst._hasAcentricFactor =  in_hasAcentricFactor;
  dst._HCRIT0 =  in_HCRIT0;
  dst._SCRIT0 =  in_SCRIT0;
  dst._deltah =  in_deltah;
  dst._deltas =  in_deltas;
  return dst;
}
*/

void Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants* src = (Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants*)(v_src);
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants* dst = (Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants*)(v_dst);
  dst->_iupacName = src->_iupacName;
  dst->_casRegistryNumber = src->_casRegistryNumber;
  dst->_chemicalFormula = src->_chemicalFormula;
  dst->_structureFormula = src->_structureFormula;
  dst->_molarMass = src->_molarMass;
  dst->_criticalTemperature = src->_criticalTemperature;
  dst->_criticalPressure = src->_criticalPressure;
  dst->_criticalMolarVolume = src->_criticalMolarVolume;
  dst->_acentricFactor = src->_acentricFactor;
  dst->_triplePointTemperature = src->_triplePointTemperature;
  dst->_triplePointPressure = src->_triplePointPressure;
  dst->_meltingPoint = src->_meltingPoint;
  dst->_normalBoilingPoint = src->_normalBoilingPoint;
  dst->_dipoleMoment = src->_dipoleMoment;
  dst->_hasIdealGasHeatCapacity = src->_hasIdealGasHeatCapacity;
  dst->_hasCriticalData = src->_hasCriticalData;
  dst->_hasDipoleMoment = src->_hasDipoleMoment;
  dst->_hasFundamentalEquation = src->_hasFundamentalEquation;
  dst->_hasLiquidHeatCapacity = src->_hasLiquidHeatCapacity;
  dst->_hasSolidHeatCapacity = src->_hasSolidHeatCapacity;
  dst->_hasAccurateViscosityData = src->_hasAccurateViscosityData;
  dst->_hasAccurateConductivityData = src->_hasAccurateConductivityData;
  dst->_hasVapourPressureCurve = src->_hasVapourPressureCurve;
  dst->_hasAcentricFactor = src->_hasAcentricFactor;
  dst->_HCRIT0 = src->_HCRIT0;
  dst->_SCRIT0 = src->_SCRIT0;
  dst->_deltah = src->_deltah;
  dst->_deltas = src->_deltas;
}

#define Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants__desc__fields[28] = {"iupacName","casRegistryNumber","chemicalFormula","structureFormula","molarMass","criticalTemperature","criticalPressure","criticalMolarVolume","acentricFactor","triplePointTemperature","triplePointPressure","meltingPoint","normalBoilingPoint","dipoleMoment","hasIdealGasHeatCapacity","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasAccurateViscosityData","hasAccurateConductivityData","hasVapourPressureCurve","hasAcentricFactor","HCRIT0","SCRIT0","deltah","deltas"};
struct record_description Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants__desc = {
  "Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.TwoPhase.FluidConstants$waterConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants__desc__fields
};

void Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants* ths = (Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants*)(v_ths);
  // ths->_iupacName has no default value.
  // ths->_casRegistryNumber has no default value.
  // ths->_chemicalFormula has no default value.
  // ths->_structureFormula has no default value.
  // ths->_molarMass has no default value.
  // ths->_criticalTemperature has no default value.
  // ths->_criticalPressure has no default value.
  // ths->_criticalMolarVolume has no default value.
  // ths->_acentricFactor has no default value.
  // ths->_triplePointTemperature has no default value.
  // ths->_triplePointPressure has no default value.
  // ths->_meltingPoint has no default value.
  // ths->_normalBoilingPoint has no default value.
  // ths->_dipoleMoment has no default value.
  ths->_hasIdealGasHeatCapacity = 0;
  ths->_hasCriticalData = 0;
  ths->_hasDipoleMoment = 0;
  ths->_hasFundamentalEquation = 0;
  ths->_hasLiquidHeatCapacity = 0;
  ths->_hasSolidHeatCapacity = 0;
  ths->_hasAccurateViscosityData = 0;
  ths->_hasAccurateConductivityData = 0;
  ths->_hasVapourPressureCurve = 0;
  ths->_hasAcentricFactor = 0;
  ths->_HCRIT0 = 0.0;
  ths->_SCRIT0 = 0.0;
  ths->_deltah = 0.0;
  ths->_deltas = 0.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants omc_Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants(threadData_t *threadData , modelica_string  in_iupacName, modelica_string  in_casRegistryNumber, modelica_string  in_chemicalFormula, modelica_string  in_structureFormula, modelica_real  in_molarMass, modelica_real  in_criticalTemperature, modelica_real  in_criticalPressure, modelica_real  in_criticalMolarVolume, modelica_real  in_acentricFactor, modelica_real  in_triplePointTemperature, modelica_real  in_triplePointPressure, modelica_real  in_meltingPoint, modelica_real  in_normalBoilingPoint, modelica_real  in_dipoleMoment, modelica_boolean  in_hasIdealGasHeatCapacity, modelica_boolean  in_hasCriticalData, modelica_boolean  in_hasDipoleMoment, modelica_boolean  in_hasFundamentalEquation, modelica_boolean  in_hasLiquidHeatCapacity, modelica_boolean  in_hasSolidHeatCapacity, modelica_boolean  in_hasAccurateViscosityData, modelica_boolean  in_hasAccurateConductivityData, modelica_boolean  in_hasVapourPressureCurve, modelica_boolean  in_hasAcentricFactor, modelica_real  in_HCRIT0, modelica_real  in_SCRIT0, modelica_real  in_deltah, modelica_real  in_deltas) {
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants_construct(threadData, dst);
  dst._iupacName =  in_iupacName;
  dst._casRegistryNumber =  in_casRegistryNumber;
  dst._chemicalFormula =  in_chemicalFormula;
  dst._structureFormula =  in_structureFormula;
  dst._molarMass =  in_molarMass;
  dst._criticalTemperature =  in_criticalTemperature;
  dst._criticalPressure =  in_criticalPressure;
  dst._criticalMolarVolume =  in_criticalMolarVolume;
  dst._acentricFactor =  in_acentricFactor;
  dst._triplePointTemperature =  in_triplePointTemperature;
  dst._triplePointPressure =  in_triplePointPressure;
  dst._meltingPoint =  in_meltingPoint;
  dst._normalBoilingPoint =  in_normalBoilingPoint;
  dst._dipoleMoment =  in_dipoleMoment;
  dst._hasIdealGasHeatCapacity =  in_hasIdealGasHeatCapacity;
  dst._hasCriticalData =  in_hasCriticalData;
  dst._hasDipoleMoment =  in_hasDipoleMoment;
  dst._hasFundamentalEquation =  in_hasFundamentalEquation;
  dst._hasLiquidHeatCapacity =  in_hasLiquidHeatCapacity;
  dst._hasSolidHeatCapacity =  in_hasSolidHeatCapacity;
  dst._hasAccurateViscosityData =  in_hasAccurateViscosityData;
  dst._hasAccurateConductivityData =  in_hasAccurateConductivityData;
  dst._hasVapourPressureCurve =  in_hasVapourPressureCurve;
  dst._hasAcentricFactor =  in_hasAcentricFactor;
  dst._HCRIT0 =  in_HCRIT0;
  dst._SCRIT0 =  in_SCRIT0;
  dst._deltah =  in_deltah;
  dst._deltas =  in_deltas;
  return dst;
}
*/

void Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants* src = (Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants*)(v_src);
  Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants* dst = (Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants*)(v_dst);
  dst->_iupacName = src->_iupacName;
  dst->_casRegistryNumber = src->_casRegistryNumber;
  dst->_chemicalFormula = src->_chemicalFormula;
  dst->_structureFormula = src->_structureFormula;
  dst->_molarMass = src->_molarMass;
  dst->_criticalTemperature = src->_criticalTemperature;
  dst->_criticalPressure = src->_criticalPressure;
  dst->_criticalMolarVolume = src->_criticalMolarVolume;
  dst->_acentricFactor = src->_acentricFactor;
  dst->_triplePointTemperature = src->_triplePointTemperature;
  dst->_triplePointPressure = src->_triplePointPressure;
  dst->_meltingPoint = src->_meltingPoint;
  dst->_normalBoilingPoint = src->_normalBoilingPoint;
  dst->_dipoleMoment = src->_dipoleMoment;
  dst->_hasIdealGasHeatCapacity = src->_hasIdealGasHeatCapacity;
  dst->_hasCriticalData = src->_hasCriticalData;
  dst->_hasDipoleMoment = src->_hasDipoleMoment;
  dst->_hasFundamentalEquation = src->_hasFundamentalEquation;
  dst->_hasLiquidHeatCapacity = src->_hasLiquidHeatCapacity;
  dst->_hasSolidHeatCapacity = src->_hasSolidHeatCapacity;
  dst->_hasAccurateViscosityData = src->_hasAccurateViscosityData;
  dst->_hasAccurateConductivityData = src->_hasAccurateConductivityData;
  dst->_hasVapourPressureCurve = src->_hasVapourPressureCurve;
  dst->_hasAcentricFactor = src->_hasAcentricFactor;
  dst->_HCRIT0 = src->_HCRIT0;
  dst->_SCRIT0 = src->_SCRIT0;
  dst->_deltah = src->_deltah;
  dst->_deltas = src->_deltas;
}

#define Modelica_Media_Water_WaterIF97__pT_FluidConstants__desc_added 1
const char* Modelica_Media_Water_WaterIF97__pT_FluidConstants__desc__fields[28] = {"iupacName","casRegistryNumber","chemicalFormula","structureFormula","molarMass","criticalTemperature","criticalPressure","criticalMolarVolume","acentricFactor","triplePointTemperature","triplePointPressure","meltingPoint","normalBoilingPoint","dipoleMoment","hasIdealGasHeatCapacity","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasAccurateViscosityData","hasAccurateConductivityData","hasVapourPressureCurve","hasAcentricFactor","HCRIT0","SCRIT0","deltah","deltas"};
struct record_description Modelica_Media_Water_WaterIF97__pT_FluidConstants__desc = {
  "Modelica_Media_Water_WaterIF97__pT_FluidConstants", /* package_record__X */
  "Modelica.Media.Water.WaterIF97_pT.FluidConstants", /* package.record_X */
  Modelica_Media_Water_WaterIF97__pT_FluidConstants__desc__fields
};

void Modelica_Media_Water_WaterIF97__pT_FluidConstants_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Water_WaterIF97__pT_FluidConstants* ths = (Modelica_Media_Water_WaterIF97__pT_FluidConstants*)(v_ths);
  // ths->_iupacName has no default value.
  // ths->_casRegistryNumber has no default value.
  // ths->_chemicalFormula has no default value.
  // ths->_structureFormula has no default value.
  // ths->_molarMass has no default value.
  // ths->_criticalTemperature has no default value.
  // ths->_criticalPressure has no default value.
  // ths->_criticalMolarVolume has no default value.
  // ths->_acentricFactor has no default value.
  // ths->_triplePointTemperature has no default value.
  // ths->_triplePointPressure has no default value.
  // ths->_meltingPoint has no default value.
  // ths->_normalBoilingPoint has no default value.
  // ths->_dipoleMoment has no default value.
  ths->_hasIdealGasHeatCapacity = 0;
  ths->_hasCriticalData = 0;
  ths->_hasDipoleMoment = 0;
  ths->_hasFundamentalEquation = 0;
  ths->_hasLiquidHeatCapacity = 0;
  ths->_hasSolidHeatCapacity = 0;
  ths->_hasAccurateViscosityData = 0;
  ths->_hasAccurateConductivityData = 0;
  ths->_hasVapourPressureCurve = 0;
  ths->_hasAcentricFactor = 0;
  ths->_HCRIT0 = 0.0;
  ths->_SCRIT0 = 0.0;
  ths->_deltah = 0.0;
  ths->_deltas = 0.0;
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Media_Water_WaterIF97__pT_FluidConstants omc_Modelica_Media_Water_WaterIF97__pT_FluidConstants(threadData_t *threadData , modelica_string  in_iupacName, modelica_string  in_casRegistryNumber, modelica_string  in_chemicalFormula, modelica_string  in_structureFormula, modelica_real  in_molarMass, modelica_real  in_criticalTemperature, modelica_real  in_criticalPressure, modelica_real  in_criticalMolarVolume, modelica_real  in_acentricFactor, modelica_real  in_triplePointTemperature, modelica_real  in_triplePointPressure, modelica_real  in_meltingPoint, modelica_real  in_normalBoilingPoint, modelica_real  in_dipoleMoment, modelica_boolean  in_hasIdealGasHeatCapacity, modelica_boolean  in_hasCriticalData, modelica_boolean  in_hasDipoleMoment, modelica_boolean  in_hasFundamentalEquation, modelica_boolean  in_hasLiquidHeatCapacity, modelica_boolean  in_hasSolidHeatCapacity, modelica_boolean  in_hasAccurateViscosityData, modelica_boolean  in_hasAccurateConductivityData, modelica_boolean  in_hasVapourPressureCurve, modelica_boolean  in_hasAcentricFactor, modelica_real  in_HCRIT0, modelica_real  in_SCRIT0, modelica_real  in_deltah, modelica_real  in_deltas) {
  Modelica_Media_Water_WaterIF97__pT_FluidConstants dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Media_Water_WaterIF97__pT_FluidConstants_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Media_Water_WaterIF97__pT_FluidConstants_construct(threadData, dst);
  dst._iupacName =  in_iupacName;
  dst._casRegistryNumber =  in_casRegistryNumber;
  dst._chemicalFormula =  in_chemicalFormula;
  dst._structureFormula =  in_structureFormula;
  dst._molarMass =  in_molarMass;
  dst._criticalTemperature =  in_criticalTemperature;
  dst._criticalPressure =  in_criticalPressure;
  dst._criticalMolarVolume =  in_criticalMolarVolume;
  dst._acentricFactor =  in_acentricFactor;
  dst._triplePointTemperature =  in_triplePointTemperature;
  dst._triplePointPressure =  in_triplePointPressure;
  dst._meltingPoint =  in_meltingPoint;
  dst._normalBoilingPoint =  in_normalBoilingPoint;
  dst._dipoleMoment =  in_dipoleMoment;
  dst._hasIdealGasHeatCapacity =  in_hasIdealGasHeatCapacity;
  dst._hasCriticalData =  in_hasCriticalData;
  dst._hasDipoleMoment =  in_hasDipoleMoment;
  dst._hasFundamentalEquation =  in_hasFundamentalEquation;
  dst._hasLiquidHeatCapacity =  in_hasLiquidHeatCapacity;
  dst._hasSolidHeatCapacity =  in_hasSolidHeatCapacity;
  dst._hasAccurateViscosityData =  in_hasAccurateViscosityData;
  dst._hasAccurateConductivityData =  in_hasAccurateConductivityData;
  dst._hasVapourPressureCurve =  in_hasVapourPressureCurve;
  dst._hasAcentricFactor =  in_hasAcentricFactor;
  dst._HCRIT0 =  in_HCRIT0;
  dst._SCRIT0 =  in_SCRIT0;
  dst._deltah =  in_deltah;
  dst._deltas =  in_deltas;
  return dst;
}
*/

void Modelica_Media_Water_WaterIF97__pT_FluidConstants_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Water_WaterIF97__pT_FluidConstants* src = (Modelica_Media_Water_WaterIF97__pT_FluidConstants*)(v_src);
  Modelica_Media_Water_WaterIF97__pT_FluidConstants* dst = (Modelica_Media_Water_WaterIF97__pT_FluidConstants*)(v_dst);
  dst->_iupacName = src->_iupacName;
  dst->_casRegistryNumber = src->_casRegistryNumber;
  dst->_chemicalFormula = src->_chemicalFormula;
  dst->_structureFormula = src->_structureFormula;
  dst->_molarMass = src->_molarMass;
  dst->_criticalTemperature = src->_criticalTemperature;
  dst->_criticalPressure = src->_criticalPressure;
  dst->_criticalMolarVolume = src->_criticalMolarVolume;
  dst->_acentricFactor = src->_acentricFactor;
  dst->_triplePointTemperature = src->_triplePointTemperature;
  dst->_triplePointPressure = src->_triplePointPressure;
  dst->_meltingPoint = src->_meltingPoint;
  dst->_normalBoilingPoint = src->_normalBoilingPoint;
  dst->_dipoleMoment = src->_dipoleMoment;
  dst->_hasIdealGasHeatCapacity = src->_hasIdealGasHeatCapacity;
  dst->_hasCriticalData = src->_hasCriticalData;
  dst->_hasDipoleMoment = src->_hasDipoleMoment;
  dst->_hasFundamentalEquation = src->_hasFundamentalEquation;
  dst->_hasLiquidHeatCapacity = src->_hasLiquidHeatCapacity;
  dst->_hasSolidHeatCapacity = src->_hasSolidHeatCapacity;
  dst->_hasAccurateViscosityData = src->_hasAccurateViscosityData;
  dst->_hasAccurateConductivityData = src->_hasAccurateConductivityData;
  dst->_hasVapourPressureCurve = src->_hasVapourPressureCurve;
  dst->_hasAcentricFactor = src->_hasAcentricFactor;
  dst->_HCRIT0 = src->_HCRIT0;
  dst->_SCRIT0 = src->_SCRIT0;
  dst->_deltah = src->_deltah;
  dst->_deltas = src->_deltas;
}

#ifdef __cplusplus
}
#endif

