/* Simulation code for MOSES.Simulations.ACTS_adsorption generated by the OpenModelica Compiler OpenModelica v1.16.5 (64-bit). */
#if !defined(MOSES_Simulations_ACTS_adsorption__MODEL_H)
#define MOSES_Simulations_ACTS_adsorption__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "MOSES.Simulations.ACTS_adsorption_functions.h"

#define MOSES_MassTransfer_sorbate_FluidConstants_index 0
#define Modelica_Media_Common_GibbsDerivs_index 1
#define Modelica_Media_Common_HelmholtzDerivs_index 2
#define Modelica_Media_Common_Helmholtz__pT_index 3
#define Modelica_Media_Common_Helmholtz__ph_index 4
#define Modelica_Media_Common_IF97BaseTwoPhase_index 5
#define Modelica_Media_Common_IF97PhaseBoundaryProperties_index 6
#define Modelica_Media_Common_NewtonDerivatives__pT_index 7
#define Modelica_Media_Common_NewtonDerivatives__ph_index 8
#define Modelica_Media_Common_PhaseBoundaryProperties_index 9
#define Modelica_Media_Common_cv2Phase_index 10
#define Modelica_Media_Common_gibbsToBoundaryProps_index 11
#define Modelica_Media_Common_helmholtzToBoundaryProps_index 12
#define Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants_index 13
#define Modelica_Media_Interfaces_Types_TwoPhase__omcQFluidConstants_24waterConstants_index 14
#define Modelica_Media_Water_IF97__Utilities_hl__p_index 15
#define Modelica_Media_Water_IF97__Utilities_hv__p_index 16
#define Modelica_Media_Water_IF97__Utilities_rhol__T_index 17
#define Modelica_Media_Water_IF97__Utilities_rhov__T_index 18
#define Modelica_Media_Water_IF97__Utilities_waterBaseProp__pT_index 19
#define Modelica_Media_Water_IF97__Utilities_waterBaseProp__ph_index 20
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_T3a__ph_index 21
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_T3b__ph_index 22
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_dptofT_index 23
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_f3_index 24
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_g1_index 25
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_g2_index 26
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_g5_index 27
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_h3ab__p_index 28
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_psat_index 29
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_tph1_index 30
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_tph2_index 31
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_tsat_index 32
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_v3a__ph_index 33
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_v3b__ph_index 34
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_dofp13_index 35
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_dofp23_index 36
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_dofpt3_index 37
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_dtofph3_index 38
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_fixdT_index 39
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Inverses_tofph5_index 40
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Isentropic_hofpT1_index 41
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Isentropic_hofpT2_index 42
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_boilingcurve__p_index 43
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_boundary23ofT_index 44
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_boundary23ofp_index 45
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_d1n_index 46
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_d2n_index 47
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_dewcurve__p_index 48
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hl__p_index 49
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hl__p__R4b_index 50
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hlowerofp1_index 51
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hlowerofp2_index 52
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hlowerofp5_index 53
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hupperofp1_index 54
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hupperofp2_index 55
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hupperofp5_index 56
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hv__p_index 57
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hv__p__R4b_index 58
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hvl__p_index 59
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_region__pT_index 60
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_region__ph_index 61
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_rhol__T_index 62
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_rhol__p__R4b_index 63
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_rhov__T_index 64
#define Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_rhov__p__R4b_index 65
#define Modelica_Media_Water_WaterIF97__pT_FluidConstants_index 66

extern void MOSES_Simulations_ACTS_adsorption_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void MOSES_Simulations_ACTS_adsorption_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void MOSES_Simulations_ACTS_adsorption_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void MOSES_Simulations_ACTS_adsorption_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int MOSES_Simulations_ACTS_adsorption_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_checkForAsserts(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int MOSES_Simulations_ACTS_adsorption_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* MOSES_Simulations_ACTS_adsorption_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* MOSES_Simulations_ACTS_adsorption_relationDescription(int i);
extern void MOSES_Simulations_ACTS_adsorption_function_initSample(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int MOSES_Simulations_ACTS_adsorption_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* MOSES_Simulations_ACTS_adsorption_linear_model_frame(void);
extern const char* MOSES_Simulations_ACTS_adsorption_linear_model_datarecovery_frame(void);
extern int MOSES_Simulations_ACTS_adsorption_mayer(DATA* data, modelica_real** res, short *);
extern int MOSES_Simulations_ACTS_adsorption_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int MOSES_Simulations_ACTS_adsorption_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int MOSES_Simulations_ACTS_adsorption_setInputData(DATA *data, const modelica_boolean file);
extern int MOSES_Simulations_ACTS_adsorption_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void MOSES_Simulations_ACTS_adsorption_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void MOSES_Simulations_ACTS_adsorption_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int MOSES_Simulations_ACTS_adsorption_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void MOSES_Simulations_ACTS_adsorption_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void MOSES_Simulations_ACTS_adsorption_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int MOSES_Simulations_ACTS_adsorption_inputNames(DATA* data, char ** names);
extern int MOSES_Simulations_ACTS_adsorption_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int MOSES_Simulations_ACTS_adsorption_functionLocalKnownVars(DATA*, threadData_t*);
extern int MOSES_Simulations_ACTS_adsorption_symbolicInlineSystem(DATA*, threadData_t*);

#include "MOSES.Simulations.ACTS_adsorption_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(MOSES_Simulations_ACTS_adsorption__MODEL_H) */


